name: Build and test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - name: xCode
      run: sudo xcode-select -s /Applications/Xcode_14.3.app/Contents/Developer/

    - uses: actions/checkout@v2
    - name: Setup .NET

      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.x.x
          7.x.x

    - name: install workload ios
      run: dotnet workload install ios

    - name: install workload wasm
      run: dotnet workload install wasm-tools

    - name: Restore dependencies
      run: dotnet restore src/Avalonia.FuncUI.sln
    - name: Build
      run: dotnet build src/Avalonia.FuncUI.sln --no-restore

    - name: Test
      run: dotnet test src/Avalonia.FuncUI.sln --no-build --verbosity normal
    
    - name: Build Templates
    run: pushd ./src/Avalonia.FuncUI.Templates && ./test-templates.ps1


