name: Build and test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - name: xCode
      run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer/

    - uses: actions/checkout@v4
    - name: Setup .NET

      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x.x
          7.x.x

    - name: install workloads
      run: dotnet workload restore src/Avalonia.FuncUI.sln

    - name: Restore dependencies
      run: dotnet restore src/Avalonia.FuncUI.sln
    - name: Build
      run: dotnet build src/Avalonia.FuncUI.sln --no-restore
    - name: Test
      run: dotnet test src/Avalonia.FuncUI.sln --no-build --verbosity normal


